version: "3.9"

name: "mkpanq"

services:
  os_base:
    image: local/os_base:latest
    build:
      context: .
      dockerfile: Dockerfile.base
  app:
    image: app:latest
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - 3000:3000
    depends_on:
      - os_base
