version: "3.9"

name: "mkpanq"

services:
  os_base:
    image: os_base
    build:
      context: .
      dockerfile: Dockerfile.base

  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - 3000:3000
    depends_on:
      os_base: service_started
