type GreetingsType = Record<string, string>;

export const greetingsData: GreetingsType = {
  english: "Hello",
  "chinese simplified": "你好",
  hindi: "नमस्ते",
  spanish: "¡Hola!",
  french: "Salut!",
  arabic: "مرحبا",
  bengali: "হ্যালো",
  portuguese: "Olá",
  urdu: "ہیلو",
  indonesian: "Halo",
  german: "Hallo",
  japanese: "こんにちは",
  punjabi: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ",
  javanese: "Halo",
  turkish: "Merhaba",
  korean: "안녕하세요",
  vietnamese: "Xin chào",
  telugu: "హలో",
  italian: "Ciao",
  marathi: "नमस्कार",
  thai: "สวัสดี",
  tamil: "வணக்கம்",
  gujarati: "નમસ્તે",
  polish: "Cześć",
  ukrainian: "Привіт",
  persian: "سلام",
  malay: "Halo",
  hausa: "Sannu",
  kannada: "ನಮಸ್ಕಾರ",
};
